/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_ffmpegdecorder_MainActivity */

#ifndef _Included_com_jack_ffmpegdecorder_MainActivity
#define _Included_com_jack_ffmpegdecorder_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jack_ffmpegdecorder_MainActivity
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_ffmpegdecorder_MainActivity_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
