/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jz_testscroll_av_AVUtil */

#ifndef _Included_com_jz_testscroll_av_AVUtil
#define _Included_com_jz_testscroll_av_AVUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jz_testscroll_av_AVUtil
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jz_testscroll_av_AVUtil_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
